# -*- coding: utf-8 -*-
"""Assignment-9/27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107hpQKXrVeSMslvj-xkCC_6n2pHV4A_q
"""

import pandas as pd

pp1 = pd.read_csv('people_1.txt', delimiter = '\t')
pp1

pp1['FirstName'] = pp1['FirstName'].str.lower().replace(' ', '',  regex = True)
pp1['LastName'] = pp1['LastName'].str.lower().replace(' ', '',  regex = True)
pp1['Email'] = pp1['Email'].str.lower().replace(' ', '',  regex = True)
pp1['Phone'] = pp1['Phone'].replace('-', '', regex = True).astype(int).replace(' ', '',  regex = True)
pp1['Address'] = pp1['Address'].str.lower().replace('no.', '', regex = True).replace('#', '', regex = True)

pp1 = pp1.drop_duplicates()
pp1

pp2 = pd.read_csv('people_2.txt', delimiter = '\t')
pp2

pp2['FirstName'] = pp2['FirstName'].str.lower().replace(' ', '',  regex = True)
pp2['LastName'] = pp2['LastName'].str.lower().replace(' ', '',  regex = True)
pp2['Email'] = pp2['Email'].str.lower().replace(' ', '',  regex = True)
pp2['Phone'] = pp2['Phone'].replace('-', '', regex = True).astype(int).replace(' ', '',  regex = True)
pp2['Address'] = pp2['Address'].str.lower().replace('no.', '', regex = True).replace('#', '', regex = True)

pp2 = pp2.drop_duplicates()
pp2

